### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by DrizzlyOwl** [Turncloak-Exile/TowerFall#1]
You need to ensure you check that certain applications are installed on the users system before using them to execute commands such as within notes.sh you are referencing leafpad.

You should look into using something like this:

``` bash
command -v leafpad >/dev/null 2>&1 || { 
    echo >&2 "I require leafpad but it's not installed.  Aborting."; 
}
sudo apt-get install leafpad
```

**Comment by Turncloak-Exile** [comment]
Enhancement

**Comment by Turncloak-Exile** [comment]
Added it to hostchanger.sh. It works fine, we're overlooking files to see where it is needed.
